In [1]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [2]:
my_house > your_house

array([ True, False, False,  True])

# Boolean Operators

In [3]:
np.logical_and(my_house > 13, your_house < 15)

array([ True, False, False, False])

In [4]:
np.logical_or(my_house > 13, your_house < 15)

array([ True,  True,  True,  True])

In [5]:
np.logical_not(my_house > 13, your_house < 15)

array([False, False,  True,  True])

# IF, ELIF, ELSE

In [6]:
# Define variables
room = "kit"
area = 14.0

In [7]:
if room == "kit" :
    print("looking around in the kitchen.")

looking around in the kitchen.


In [8]:
x = 'iqram/haris/fahromi'